
export const sample_products: any[] = [
    {
        id:1,
        productName:"Redmi Note 8 pro",
        productDescription:"Téléphone haut de gamme 8go de RAM, 128Go de stockage",
        productPrice:500000,
        productCategory:"Technologie",
        productUnite:"pièce",
        productStock:1,
        productState:"Nouveau",
        productSource:"Chine",
        productImage:"redmi-note-8-foret-verte.webp",
      },
      {
        id:2,
        productName:"Chaise de bureau",
        productDescription:"Confortable et ajustable, idéale pour travailler",
        productPrice:400000,
        productCategory:"Meubles",
        productUnite:"pièces",
        productStock:1,
        productState:"Nouveau",
        productSource:"France",
        productImage:"Chaise debureau.png",
      },
      {
        id:3,
        productName:"Gant de boxe",
        productDescription:"Gant professionnel, respectant les normes et utilisable dans les combats officiels",
        productPrice:150000,
        productCategory:"Sport",
        productUnite:"paires",
        productStock:1,
        productState:"",
        productSource:"Thailand",
        productImage:"boxing gloves.jpg",
      },
      {
        id:4,
        productName:"Chaussure Sneaker",
        productDescription:"Souple et résistance idéal pour de longue promenade en ville ou en forêt",
        productPrice:200000,
        productCategory:"Sport",
        productUnite:"paires",
        productStock:1,
        productState:"",
        productSource:"France",
        productImage:"Sneaker-for-Men-Shoes.jpg",
      },
      {
        id:5,
        productName:"BMW E46 phase 2",
        productDescription:"Faible kilométrage citadine et luxueuse",
        productPrice:18000000,
        productCategory:"Vehicule",
        productUnite:"",
        productStock:1,
        productState:"",
        productSource:"France",
        productImage:"BMW_E46_front_20080328.jpg",
      },
      {
        id:6,
        productName:"Peugeot 306",
        productDescription:"Voiture occasion très bonne état, aucun devoir prévu",
        productPrice:8800000,
        productCategory:"Vehicule",
        productUnite:"",
        productStock:1,
        productState:"Speciale",
        productSource:"France",
        productImage:"peugeot 306.jpg",
      },
]
export const sample_categories: any[] = [
    {CatName: 'Meubles'},
    {CatName: 'Technologie'},
    {CatName: 'Sport'},
    {CatName: 'Immobilier'},
    {CatName: 'Vehicule'},
    {CatName: 'Services'},
]