export interface ICorporateUserRegister{
    raisonSocial : string;
    type : string;
    rcs : string;
    carteStat : string;
    nif : string;
    carteFiscal : string;
    logo : string;
    managerName : string;
    managerEmail : string;
    contactName : string;
    contactPhone : string;
    contactEmail : string;
    siegeAddress : string;
    siegeLat : string;
    siegeLng : string;
    contactEmailVerified : string;
    corporateUserValidated : string;
    userTotalSolde : number;
    userAccess : string;
}